/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'samrudhinayak' at '9/12/16 1:30 PM' with Gradle 2.14.1
 *
 * @author samrudhinayak, @date 9/12/16 1:30 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
